### ISSUE TITLE
Ignore dependencies which are a workspace member

### ISSUE THREAD

**Issue by jayvdb** [trailofbits/cargo-unmaintained#277]
In our workspace Cargo.toml we have each member listed in `[dependencies]` as `memberA = { path = "..." }`

Then memberB's Cargo.toml it includes `memberA.workspace = true`

And cargo-unmaintained lists them as `(no repository)`.

**Comment by smoelius** [comment]
Are the workspace members published to crates.io?

**Comment by jayvdb** [comment]
no, they are not published to any registry.

They are specified by `path = ` only.

**Comment by smoelius** [comment]
Sorry, but I don't quite understand the issue. Could you share the warning that is produced, possibly redacted?

Also, in your description, I don't understand the relationship between `memberA` and `memberB`. Is the following really what you meant to write?

> Then memberB's Cargo.toml it includes `memberA.workspace = true`

I don't understand what it means for memberB's Cargo.toml to include that syntax. Could you maybe share an actual snippet from memberB's Cargo.toml, again possibly redacted?

Part of my confusion stems from the fact that dependencies specified by path appear to already be ignored: https://github.com/trailofbits/cargo-unmaintained/blob/9b39e320b263910b2a4dc57f0fe6dd6027d7f6fd/src/main.rs#L639-L642

**Comment by jayvdb** [comment]
Yes, I meant to write `memberA.workspace = true` which is the same as `memberA = { workspace = true }`.

top level `Cargo.toml`:

```toml
[workspace.dependences]
memberA = { path = "path/to/memberA" }
memberB = { path = "path/to/memberB" }

[workspace]
members = [
  "path/to/memberA",
  "path/to/memberB",
]
```

`path/to/memberB/Cargo.toml`:

```toml
[dependencies]
memberA.workspace = true
```

`memberB` depends on `memberA`, which is described in the top level `Cargo.toml`.
